version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentex
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentex
    restart: always
    ports: 
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
    links: 
      - postgres
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local